set(CODASH_USER_URL https://github.com/eile/codash.git)
set(COLLAGE_USER_URL https://github.com/eile/Collage.git)
set(EXTRACELLULAR_USER_URL ssh://bbpgit.epfl.ch/user/eilemann/extracellular.git)
set(LIVRE_USER_URL https://github.com/eile/Livre.git)
set(LUNCHBOX_USER_URL https://github.com/eile/Lunchbox.git)
set(QT_STEERER_USER_URL https://github.com/eile/qt_steerer.git)
set(STEER_LIB_USER_URL https://github.com/eile/steer_lib.git)
set(VMMLIB_USER_URL https://github.com/Eyescale/vmmlib.git)
