set(LUNCHBOX_FORCE_BUILD 1)
set(EQUALIZER_FORCE_BUILD 1)
set(VMMLIB_FORCE_BUILD 1)
set(GPU-SD_FORCE_BUILD 1)

set(FLATINDEX_REPO_TAG eile-speedST)

set(BBPSDK_REPO_TAG before_brion)
list(APPEND BBPSDK_DEPENDS REQUIRED HDF5)
set(BBPSDK_HDF5_COMPONENTS "C CXX")

set(BUILDYARD_TRAVIS_CONFIG
 "https://github.com/Bluebrain/config.git config.bluebrain")
